service: user

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  endpointType: REGIONAL
  stage: dev
  environment:
    USER_TABLE: ${self:service}-${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE}'

functions:
  createUser:
    handler: src/handlers/create/create.handler
    memorySize: 128
    description: Create a user
    events:
      - http:
          path: user
          method: post
          request:
            schema:
              application/json: ${file(src/handlers/create/validator.json)}

resources:
  Resources:
    DynamoDbUserTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: 'NEW_AND_OLD_IMAGES'
        TableName: ${self:provider.environment.USER_TABLE}
